### PR TITLE
switch back to arkworks field arithmetic for 64-bit backend

### LINKED ISSUE #101: switch back to arkworks field arithmetic for 64-bit backend
As part of https://github.com/penumbra-zone/penumbra/issues/3526, we added `fiat-crypto` formally verified field arithmetic implementations to `decaf377`, moving away from using the Arkworks field arithmetic imlpementation. This unblocked development of Penumbra's ledger app, since the Arkworks field arithmetic allocated.

However, @TalDerei did some very helpful benchmarking [here](https://github.com/penumbra-zone/penumbra/pull/3806#issuecomment-1985092416) and found that we have a significant performance regression. 

This performance regression is blocking migrating downstream crates to the latest stable release (0.9.0, see #93). To move forward without introducing a performance regression we should switch back to Arkworks field arithmetic for the 64-bit backend *only*. Embedded environments like Ledger development will use the 32-bit backend which will continue to use the formally verified `fiat-crypto` field arithmetic.

### PR DESCRIPTION
**Pull request by redshiftzero**
Closes #101

### CODE REVIEW

**Comment by redshiftzero** [comment]
The remaining work here is to figure out why the tests are failing - they are the r1cs feature tests only so likely to be something wrong with Fp

File: src/fields/fp/u64/wrapper.rs [hunk 1]
```diff
@@ -27,174 +25,97 @@ impl zeroize::Zeroize for Fp {
...
+        let mut bytes = [0u8; 48];
+        self.0
+            .serialize_compressed(&mut bytes[..])
+            .expect("serialization into array should be infallible");
         bytes
     }
 
     pub(crate) const fn from_montgomery_limbs(limbs: [u64; N]) -> Fp {
-        Self(fiat::FpMontgomeryDomainFieldElement(limbs))
+        Self(ArkworksFp::new_unchecked(BigInt::new(limbs)))
```
Comment (TalDerei) [inline src/fields/fp/u64/wrapper.rs:70]: can it be simplified to `Self(ArkworksFp::new_unchecked(BigInt(limbs)))`?

File: src/fields/fp/u64/wrapper.rs [hunk 2]
```diff
@@ -27,174 +25,97 @@ impl zeroize::Zeroize for Fp {
...
+    ]);
 
     pub fn square(&self) -> Fp {
-        let mut result = fiat::FpMontgomeryDomainFieldElement([0; N]);
-        fiat::fp_square(&mut result, &self.0);
-        Self(result)
+        Fp(self.0.square())
     }
 
     pub fn inverse(&self) -> Option<Self> {
```
Comment (TalDerei) [inline src/fields/fp/u64/wrapper.rs:98]: the `fiat-crypto` generated `inverse` implementation was extremely slow (~8x) compared to arkworks in 64-bit backend.

File: src/fields/fq/u64/wrapper.rs [hunk 3]
```diff
@@ -36,55 +31,61 @@ impl zeroize::Zeroize for Fq {
...
+            .expect("serialization into array should be infallible");
         bytes
     }
 
     /// Instantiate a constant field element from its montgomery limbs.
     ///
     /// This should only be used if you are familiar with the internals of the library.
     pub const fn from_montgomery_limbs(limbs: [u64; N]) -> Fq {
-        Self(fiat::FqMontgomeryDomainFieldElement(limbs))
+        // The Arkworks `Fp::new_unchecked` method does not perform montgomery reduction.
```
Comment (TalDerei) [inline src/fields/fq/u64/wrapper.rs:83]: just for clarification, we don't perform montgomery reduction because the function is intended to handle limbs that are already in montgomery form?

**Review by TalDerei — APPROVED** [review]
this looks good, nice work! 

will propagate the updated dep versions to https://github.com/penumbra-zone/penumbra/pull/3806 once we cut a release

File: src/fields/fq/u64/wrapper.rs (hunk 3 above)
Comment (redshiftzero) [reply src/fields/fq/u64/wrapper.rs:83]: yep exactly
